// <auto-generated />
using System;
using G_StockVente.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace G_StockVente.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260110130535_AddDelegation")]
    partial class AddDelegation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserBoutique", b =>
                {
                    b.Property<Guid>("BoutiquesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateursId")
                        .HasColumnType("uuid");

                    b.HasKey("BoutiquesId", "UtilisateursId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("ApplicationUserBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Achat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReceptionPrevue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FournisseurId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroAchat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroFactureFournisseur")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("BoutiqueId", "NumeroAchat")
                        .IsUnique();

                    b.ToTable("Achats");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BoutiqueActiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueActiveId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Boutique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TvaParDefaut")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Boutiques");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CategorieParenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieParenteId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Delegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Raison")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RoleDelege")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UtilisateurBeneficiaireId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurDelegantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurBeneficiaireId", "EstActive", "DateDebut", "DateFin");

                    b.HasIndex("UtilisateurDelegantId", "UtilisateurBeneficiaireId", "RoleDelege", "DateDebut", "DateFin");

                    b.ToTable("Delegations");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueId", "Nom")
                        .IsUnique();

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Fournisseur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Inventaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinalisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroInventaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("BoutiqueId", "NumeroInventaire")
                        .IsUnique();

                    b.ToTable("Inventaires");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.JournalConnexion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateTentative")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RaisonEchec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Succes")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email", "DateTentative");

                    b.HasIndex("UtilisateurId", "DateTentative");

                    b.ToTable("JournalConnexions");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneAchat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AchatId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantiteCommandee")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteRecue")
                        .HasColumnType("integer");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AchatId");

                    b.HasIndex("ProduitBoutiqueId");

                    b.ToTable("LignesAchat");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneInventaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CommentaireEcart")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InventaireId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantiteReelle")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteTheorique")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventaireId");

                    b.HasIndex("ProduitBoutiqueId");

                    b.ToTable("LignesInventaire");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneTransfertStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantiteRecue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransfertStockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProduitBoutiqueId");

                    b.HasIndex("TransfertStockId");

                    b.ToTable("LignesTransfertStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneVente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<decimal>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("VenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProduitBoutiqueId");

                    b.HasIndex("VenteId");

                    b.ToTable("LignesVente");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.MouvementStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AchatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventaireId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransfertStockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchatId");

                    b.HasIndex("DepotId");

                    b.HasIndex("InventaireId");

                    b.HasIndex("ProduitBoutiqueId");

                    b.HasIndex("TransfertStockId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("VenteId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<string>("LienAction")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueId");

                    b.HasIndex("UtilisateurId", "EstLue", "DateCreation");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.PaiementIntegre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonneesReponse")
                        .HasColumnType("text");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceExterne")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceExterne");

                    b.HasIndex("VenteId");

                    b.ToTable("PaiementsIntegres");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ProduitBoutique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeBarres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeuilStockBas")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("BoutiqueId", "CodeBarres")
                        .IsUnique()
                        .HasFilter("\"CodeBarres\" IS NOT NULL AND \"CodeBarres\" != ''");

                    b.HasIndex("BoutiqueId", "Sku")
                        .IsUnique()
                        .HasFilter("\"Sku\" IS NOT NULL AND \"Sku\" != ''");

                    b.ToTable("ProduitsBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.RapportProgramme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailDestinataire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Frequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProchaineExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeRapport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurCreateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueId");

                    b.HasIndex("UtilisateurCreateurId");

                    b.ToTable("RapportsProgrammes");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateDerniereMaj")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProduitBoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ProduitBoutiqueId", "DepotId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.TransfertStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BoutiqueDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoutiqueSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepotDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepotSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurCreateurId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UtilisateurRecepteurId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UtilisateurValidateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueDestinationId");

                    b.HasIndex("DepotDestinationId");

                    b.HasIndex("DepotSourceId");

                    b.HasIndex("UtilisateurCreateurId");

                    b.HasIndex("UtilisateurRecepteurId");

                    b.HasIndex("UtilisateurValidateurId");

                    b.HasIndex("BoutiqueSourceId", "Numero")
                        .IsUnique()
                        .HasFilter("\"BoutiqueSourceId\" IS NOT NULL");

                    b.ToTable("TransfertsStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Vente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroVente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurAnnulationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurAnnulationId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("BoutiqueId", "NumeroVente")
                        .IsUnique();

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUserBoutique", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", null)
                        .WithMany()
                        .HasForeignKey("BoutiquesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Achat", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany("Achats")
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Fournisseur", "Fournisseur")
                        .WithMany("Achats")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany("Achats")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("Fournisseur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ApplicationUser", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "BoutiqueActive")
                        .WithMany()
                        .HasForeignKey("BoutiqueActiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoutiqueActive");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Categorie", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Categorie", "CategorieParente")
                        .WithMany("SousCategories")
                        .HasForeignKey("CategorieParenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieParente");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Delegation", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurBeneficiaire")
                        .WithMany()
                        .HasForeignKey("UtilisateurBeneficiaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurDelegant")
                        .WithMany()
                        .HasForeignKey("UtilisateurDelegantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilisateurBeneficiaire");

                    b.Navigation("UtilisateurDelegant");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Depot", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany("Depots")
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Inventaire", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany("Inventaires")
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Depot", "Depot")
                        .WithMany("Inventaires")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany("Inventaires")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("Depot");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.JournalConnexion", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneAchat", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Achat", "Achat")
                        .WithMany("LignesAchat")
                        .HasForeignKey("AchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany("LignesAchat")
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achat");

                    b.Navigation("ProduitBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneInventaire", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Inventaire", "Inventaire")
                        .WithMany("LignesInventaire")
                        .HasForeignKey("InventaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany()
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventaire");

                    b.Navigation("ProduitBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneTransfertStock", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany()
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.TransfertStock", "TransfertStock")
                        .WithMany("LignesTransfert")
                        .HasForeignKey("TransfertStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitBoutique");

                    b.Navigation("TransfertStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.LigneVente", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany("LignesVente")
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Vente", "Vente")
                        .WithMany("LignesVente")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitBoutique");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.MouvementStock", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Achat", "Achat")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("AchatId");

                    b.HasOne("G_StockVente.Domain.Models.Depot", "Depot")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Inventaire", "Inventaire")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("InventaireId");

                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.TransfertStock", "TransfertStock")
                        .WithMany()
                        .HasForeignKey("TransfertStockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Vente", "Vente")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("VenteId");

                    b.Navigation("Achat");

                    b.Navigation("Depot");

                    b.Navigation("Inventaire");

                    b.Navigation("ProduitBoutique");

                    b.Navigation("TransfertStock");

                    b.Navigation("Utilisateur");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Notification", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany()
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Boutique");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.PaiementIntegre", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Vente", "Vente")
                        .WithMany("PaiementsIntegres")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Produit", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ProduitBoutique", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany("ProduitsBoutique")
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Produit", "Produit")
                        .WithMany("ProduitsBoutique")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.RapportProgramme", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany()
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurCreateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurCreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("UtilisateurCreateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Stock", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Depot", "Depot")
                        .WithMany("Stocks")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ProduitBoutique", "ProduitBoutique")
                        .WithMany("Stocks")
                        .HasForeignKey("ProduitBoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("ProduitBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.TransfertStock", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "BoutiqueDestination")
                        .WithMany()
                        .HasForeignKey("BoutiqueDestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G_StockVente.Domain.Models.Boutique", "BoutiqueSource")
                        .WithMany()
                        .HasForeignKey("BoutiqueSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G_StockVente.Domain.Models.Depot", "DepotDestination")
                        .WithMany()
                        .HasForeignKey("DepotDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.Depot", "DepotSource")
                        .WithMany()
                        .HasForeignKey("DepotSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurCreateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurCreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurRecepteur")
                        .WithMany()
                        .HasForeignKey("UtilisateurRecepteurId");

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurValidateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurValidateurId");

                    b.Navigation("BoutiqueDestination");

                    b.Navigation("BoutiqueSource");

                    b.Navigation("DepotDestination");

                    b.Navigation("DepotSource");

                    b.Navigation("UtilisateurCreateur");

                    b.Navigation("UtilisateurRecepteur");

                    b.Navigation("UtilisateurValidateur");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Vente", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.Boutique", "Boutique")
                        .WithMany("Ventes")
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "UtilisateurAnnulation")
                        .WithMany()
                        .HasForeignKey("UtilisateurAnnulationId");

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", "Utilisateur")
                        .WithMany("Ventes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("Utilisateur");

                    b.Navigation("UtilisateurAnnulation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("G_StockVente.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Achat", b =>
                {
                    b.Navigation("LignesAchat");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Inventaires");

                    b.Navigation("MouvementsStock");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Boutique", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Depots");

                    b.Navigation("Inventaires");

                    b.Navigation("ProduitsBoutique");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Categorie", b =>
                {
                    b.Navigation("Produits");

                    b.Navigation("SousCategories");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Depot", b =>
                {
                    b.Navigation("Inventaires");

                    b.Navigation("MouvementsStock");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Fournisseur", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Inventaire", b =>
                {
                    b.Navigation("LignesInventaire");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Produit", b =>
                {
                    b.Navigation("ProduitsBoutique");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.ProduitBoutique", b =>
                {
                    b.Navigation("LignesAchat");

                    b.Navigation("LignesVente");

                    b.Navigation("MouvementsStock");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.TransfertStock", b =>
                {
                    b.Navigation("LignesTransfert");
                });

            modelBuilder.Entity("G_StockVente.Domain.Models.Vente", b =>
                {
                    b.Navigation("LignesVente");

                    b.Navigation("MouvementsStock");

                    b.Navigation("PaiementsIntegres");
                });
#pragma warning restore 612, 618
        }
    }
}
